mission_state_machine_node:
  ros__parameters:
    takeoff_altitude: 10.0
    cruise_altitude: 10.0
    land_altitude: 0.4
    arrival_tolerance: 8.0
    explore_timeout_s: 420.0
    desired_lantern_count: 4
    takeoff_timeout_s: 20.0
    entrance_timeout_s: 60.0
    return_timeout_s: 180.0
    land_timeout_s: 120.0
    mission_hard_timeout_s: 1200.0
    completion_grace_s: 2.0
    entrance_waypoints: [-38.0, 10.0, 10.0, -1.57, -55.0, 0.84, 15.0, -1.57]
    explore_waypoints: [-80.0, -130.0, -200.0]
