voxel_grid_mapper_node:
  ros__parameters:
    resolution: 0.5
    frame_id: "world"
    point_stride: 8
    serialization_voxel_limit: 20000   # TODO: tune
    min_frontier_altitude_m: 2.0
    max_frontier_altitude_m: 35.0
    frontier_republish_distance_m: 3.0  # TODO: tune
    frontier_x_bias: 0.35               # TODO: tune
